<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BusyBee-PC" name="test2" tests="4" failures="1" timestamp="12 Nov 2019 07:40:42 GMT" time="28.539" errors="0">
  <testcase name="a1" time="0.0" classname="com.learning.testng.Multiple_Test2">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.learning.testng.Multiple_Test2.a1(Multiple_Test2.java:46)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- a1 -->
  <testcase name="b1" time="0.0" classname="com.learning.testng.Multiple_Test2"/>
  <testcase name="c1" time="0.0" classname="com.learning.testng.Multiple_Test2"/>
  <testcase name="m1" time="28.524" classname="com.learning.testng.Multiple_Test2"/>
</testsuite> <!-- test2 -->
